In [1]:
import csv
import pandas as pd
import math 
import itertools

In [2]:
df=pd.read_csv("https://s3.amazonaws.com/istreet-questions-us-east-1/443606/census.csv",header=None)

In [3]:
df

,0,1,2,3,4,5,6,7,8,9,10,11
0,age=Middle-aged,sex=Male,education=Bachelors,native-country=United-States,race=White,marital-status=Never-married,workclass=State-gov,occupation=Adm-clerical,hours-per-week=Full-time,income=Small,capital-gain=Low,capital-loss=None
1,age=Senior,sex=Male,education=Bachelors,native-country=United-States,race=White,marital-status=Married-civ-spouse,workclass=Self-emp-not-inc,occupation=Exec-managerial,hours-per-week=Part-time,income=Small,capital-gain=None,capital-loss=None
2,age=Middle-aged,sex=Male,education=HS-grad,native-country=United-States,race=White,marital-status=Divorced,workclass=Private,occupation=Handlers-cleaners,hours-per-week=Full-time,income=Small,capital-gain=None,capital-loss=None
3,age=Senior,sex=Male,education=11th,native-country=United-States,race=Black,marital-status=Married-civ-spouse,workclass=Private,occupation=Handlers-cleaners,hours-per-week=Full-time,income=Small,capital-gain=None,capital-loss=None
4,age=Middle-aged,sex=Female,education=Bachelors,native-country=Cuba,race=Black,marital-status=Married-civ-spouse,workclass=Private,occupation=Prof-specialty,hours-per-week=Full-time,income=Small,capital-gain=None,capital-loss=None
...,...,...,...,...,...,...,...,...,...,...,...,...
30157,age=Middle-aged,sex=Female,education=Assoc-acdm,native-country=United-States,race=White,marital-status=Married-civ-spouse,workclass=Private,occupation=Tech-support,hours-per-week=Full-time,income=Small,capital-gain=None,capital-loss=None
30158,age=Middle-aged,sex=Male,education=HS-grad,native-country=United-States,race=White,marital-status=Married-civ-spouse,workclass=Private,occupation=Machine-op-inspct,hours-per-week=Full-time,income=Large,capital-gain=None,capital-loss=None
30159,age=Senior,sex=Female,education=HS-grad,native-country=United-States,race=White,marital-status=Widowed,workclass=Private,occupation=Adm-clerical,hours-per-week=Full-time,income=Small,capital-gain=None,capital-loss=None
30160,age=Young,sex=Male,education=HS-grad,native-country=United-States,race=White,marital-status=Never-married,workclass=Private,occupation=Adm-clerical,hours-per-week=Part-time,income=Small,capital-gain=None,capital-loss=None
30161,age=Senior,sex=Female,education=HS-grad,native-country=United-States,race=White,marital-status=Married-civ-spouse,workclass=Self-emp-inc,occupation=Exec-managerial,hours-per-week=Full-time,income=Large,capital-gain=High,capital-loss=None

In [5]:
label = ['age','sex','education','country','race','status',  'workclass','occupation','hours-per-week','income','capital-gain','capital-loss']

In [7]:
df.columns = label
total = len(df.index)

In [8]:
df

,age,sex,education,country,race,status,workclass,occupation,hours-per-week,income,capital-gain,capital-loss
0,age=Middle-aged,sex=Male,education=Bachelors,native-country=United-States,race=White,marital-status=Never-married,workclass=State-gov,occupation=Adm-clerical,hours-per-week=Full-time,income=Small,capital-gain=Low,capital-loss=None
1,age=Senior,sex=Male,education=Bachelors,native-country=United-States,race=White,marital-status=Married-civ-spouse,workclass=Self-emp-not-inc,occupation=Exec-managerial,hours-per-week=Part-time,income=Small,capital-gain=None,capital-loss=None
2,age=Middle-aged,sex=Male,education=HS-grad,native-country=United-States,race=White,marital-status=Divorced,workclass=Private,occupation=Handlers-cleaners,hours-per-week=Full-time,income=Small,capital-gain=None,capital-loss=None
3,age=Senior,sex=Male,education=11th,native-country=United-States,race=Black,marital-status=Married-civ-spouse,workclass=Private,occupation=Handlers-cleaners,hours-per-week=Full-time,income=Small,capital-gain=None,capital-loss=None
4,age=Middle-aged,sex=Female,education=Bachelors,native-country=Cuba,race=Black,marital-status=Married-civ-spouse,workclass=Private,occupation=Prof-specialty,hours-per-week=Full-time,income=Small,capital-gain=None,capital-loss=None
...,...,...,...,...,...,...,...,...,...,...,...,...
30157,age=Middle-aged,sex=Female,education=Assoc-acdm,native-country=United-States,race=White,marital-status=Married-civ-spouse,workclass=Private,occupation=Tech-support,hours-per-week=Full-time,income=Small,capital-gain=None,capital-loss=None
30158,age=Middle-aged,sex=Male,education=HS-grad,native-country=United-States,race=White,marital-status=Married-civ-spouse,workclass=Private,occupation=Machine-op-inspct,hours-per-week=Full-time,income=Large,capital-gain=None,capital-loss=None
30159,age=Senior,sex=Female,education=HS-grad,native-country=United-States,race=White,marital-status=Widowed,workclass=Private,occupation=Adm-clerical,hours-per-week=Full-time,income=Small,capital-gain=None,capital-loss=None
30160,age=Young,sex=Male,education=HS-grad,native-country=United-States,race=White,marital-status=Never-married,workclass=Private,occupation=Adm-clerical,hours-per-week=Part-time,income=Small,capital-gain=None,capital-loss=None
30161,age=Senior,sex=Female,education=HS-grad,native-country=United-States,race=White,marital-status=Married-civ-spouse,workclass=Self-emp-inc,occupation=Exec-managerial,hours-per-week=Full-time,income=Large,capital-gain=High,capital-loss=None